coverage_service: cobertura_xml
ignore:
  - "Good NewsTest/*"
  - "Good News/Common/*"
  - "*Node.swift"
  - "*Node.swift"
  - "*Service.swift"
  - "*ServiceProtocol.swift"
  - "*RequestResult.swift"
output_directory: ./
scheme: "Good News"
xcodeproj: "Good News.xcodeproj"
workspace: "Good News.xcworkspace"
