coverage_service: cobertura_xml
xcodeproj: Good\ News.xcworkspace
scheme: Good\ News
output_directory: ./
ignore:
  - Good\ NewsTest/*
  - Good\ News/Common/*
  - *Node.swift
  - *Service.swift
  - *ServiceProtocol.swift
  - *RequestResult.swift
