name: Handle Dependabot Alert

on:
  repository_dispatch:
  push:

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait to Ensure Logs are Ready
        run: sleep 10s
        shell: bash

      - name: Set Up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          if [ -f .github/requirements-dependabot.txt ]; then
            pip install -r .github/requirements-dependabot.txt
          else
            echo "No requirements-dependabot.txt found, skipping dependency installation."
          fi

      - name: Run Dependabot Processor
        env:
          githubToken: ${{ secrets.DEPENDABOT_TEST_CLASSIC }}
          slackWebHookURL: ${{ secrets.SLACK }}
          codeCommitter: ${{ github.actor }}
          commitSHA: ${{ github.sha }}
          repoName: ${{ github.repository }}
          branchName: ${{ github.ref }}
        run: |
          cp "${{ github.workspace }}/notification/slack_new.py" "${{ github.workspace }}/.github/slack.py"

          if [ -f "${{ github.workspace }}/.github/security-dependabot-events.py" ] && [ -f "${{ github.workspace }}/.github/slack.py" ]; then
            cd "${{ github.workspace }}/.github" && python security-dependabot-events.py
          else
            echo "security-dependabot-events.py or slack.py script not found, skipping execution."
          fi

