name: Handle Dependabot Alert
on:
  repository_dispatch:
  workflow_dispatch:
  issues:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: write

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Payload
        run: echo "${{ github.head_repository.downloads_url }}"
        
      - name: Print GitHub Event Payload
        run: echo '${{ toJson(github.event) }}'
