name: Handle Dependabot Alert
on:
  dependabot_alert:  # This listens directly for dependabot alerts.
    types: [dismissed]
jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Payload
        run: echo "${{ toJson(github.event) }}"
