name: Handle Dependabot Alert
on:
  repository_dispatch:
  workflow_dispatch:
  issues:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: write

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Payload
        run: echo "${{ github.head_repository.downloads_url }}"
        
      - name: Print GitHub Event Payload
        run: echo '${{ toJson(github.event) }}'
        
      - name: Print Logs URL
        run: echo '${{ toJson(github.event.workflow_run.logs_url) }}'
        
      - name: Download Workflow Logs
        env:
          DEPENDABOT_TEST: ${{ secrets.DEPENDABOT_TEST }}
        run: |
          curl -L -H "Authorization: token $DEPENDABOT_TEST" \
               -H "Accept: application/vnd.github+json" \
               "${{ github.event.workflow_run.logs_url }}" \
               -o logs.zip

          unzip logs.zip -d logs
          ls -R logs


