name: Handle Dependabot Alert
on:
  repository_dispatch:
      types:
        - webhook
permissions:
  contents: write

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Payload
        run: echo "${{ toJson(github.event) }}"
