name: Swift

on:
  repository_dispatch:
    types: [dependabot_alert]
  

jobs:
  process_dependabot_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Check Dependabot alert action
        if: github.event.action == 'open'
        run: |
          echo "A new Dependabot alert has been created."
