name: Receive Event from GitHub App
on:
  repository_dispatch:
    types: [custom-event]
jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Payload
        run: echo "${{ toJson(github.event) }}"
