name: Handle Dependabot Alert
on:
  repository_dispatch:
  workflow_dispatch:
  issues:
  workflow_run:
    workflows: ["UnitTest"]
    types:
      - completed

permissions:
  contents: write

jobs:
  handle-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Payload
        run: echo "${{ github.event.workflow_run }}"
