name: UnitTest

on:
  workflow_dispatch:
  push:
    branches:
      - master

# env:
#   DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer


jobs:
  unit_test:
    name: Unit Testing Pipeline
    runs-on: macOS-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    outputs:
      action-url: ${{ steps.getActionUrl.outputs.actionUrl }}

    steps:
      - name: Get action url
        id: getActionUrl
        run: |
          actionUrl="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}/"
          echo "actionUrl=$actionUrl" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v2
        
      # - name: Test Results
      #   uses: kishikawakatsumi/xcresulttool@v1.7.1
      #   with:
      #     path: UnitTestResults.xcresult
      #   #if: success() || failure()

      - name: Use xcresulttool from local repo
        uses: DevOps-ManiInspire/swift
        with:
          path: UnitTestResults.xcresult
          title: Xcode test results
          show-passed-tests: false
          show-code-coverage: true
          upload-bundles: always
          token: ${{ secrets.SWIFT_TOKEN_APP }}
        if: success() || failure()
